pipeline {
	agent any
	parameters {
		string(name: 'VERSION', description: 'Which version to call the RC')
	}
	environment {
		majorVersion = "1"
		minorVersion = "8"
		urlBase = "https://www.crosswire.org/svn/sword/branches/sword-1-8-x/"
		targetDirectory = "sword-${VERSION}"
	}

	stages {
		stage("Export") {
			steps {
				createTarball()
			}
		}

		stage("Build test") {
			parallel {
				stage("autotools") {
					agent any
					steps {
						buildSword("autotools")
					}
				}
				stage("CMake") {
					agent any
					steps {
						buildSword("cmake")
					}
				}
			}
		}

		stage("Deploy artifact") {
			steps {
				cleanWs()
				unstash "build"
				sh "cp '${targetDirectory}.tar.gz' '${ALPHA_DIR}/'"
				archiveArtifacts "${targetDirectory}.tar.gz"
			}
		}
	}
}
