pipeline {
	agent any
	parameters {
		string(name: 'VERSION', description: 'Which version to call the RC')
	}
	environment {
		majorVersion = "1"
		minorVersion = "8"
		urlBase = "https://www.crosswire.org/svn/sword/sword-1-8-x/"
		targetDirectory = "sword-${VERSION}"
	}

	stages {
		stage("Export") {
			steps {
				cleanWs()
				sh "svn export '${urlBase}' '${targetDirectory}'"
				sh "cd '${targetDirectory}/scripts' && ./mkswordtar"
				stash name: "build", includes: "${targetDirectory}.tar.gz"
			}
		}

		stage("Build test") {
			parallel {
				stage("autotools") {
					agent any
					environment {
						FLAVOR = "autotools"
					}
					steps {
						cleanWs()
						unstash "build"
						sh "tar xaf ${targetDirectory}.tar.gz"
						dir("sword-scripts") {
							checkout scm
						}
						dir(targetDirectory) {
							sh "${WORKSPACE}/sword-scripts/scripts/autobuild.sh"
						}
						sh "${WORKSPACE}/sword-scripts/scripts/test.sh"
					}
				}
				stage("CMake") {
					agent any
					environment {
						FLAVOR = "cmake"
					}
					steps {
						cleanWs()
						unstash "build"
						sh "tar xaf ${targetDirectory}.tar.gz"
						dir("sword-scripts") {
							checkout scm
						}
						dir(targetDirectory) {
							sh "${WORKSPACE}/sword-scripts/scripts/cmake.sh"
						}
						sh "${WORKSPACE}/sword-scripts/scripts/test.sh"
					}
				}
			}
		}

		stage("Deploy artifact") {
			steps {
				cleanWs()
				unstash "build"
				//sh "cp '${targetDirectory}.tar.gz' '${RELEASE_DIR}/v${majorVersion}.${minorVersion}'"
				sh "ls -lR ${RELEASE_DIR}"
				archiveArtifacts "${targetDirectory}.tar.gz"
			}
		}
	}
}
