pipeline {
	agent any
	parameters {
		string(name: 'VERSION', description: 'The SVN version to checkout')
	}
	environment {
		TAG_BASE = env.VERSION.replaceAll("\\.", "-")
		TAG = "sword-${TAG_BASE}"
		majorVersion = env.VERSION.split("\\.")[0]
		minorVersion = env.VERSION.split("\\.")[1]
		urlBase = "https://www.crosswire.org/svn/sword/tags/${TAG}"
		targetDirectory = "sword-${VERSION}"
	}

	stages {
		stage("Export") {
			steps {
				cleanWs()
				sh "svn export '${urlBase}' '${targetDirectory}'"
				sh "cd '${targetDirectory}/scripts' && ./mkswordtar"
				stash name: "build", includes: "${targetDirectory}.tar.gz"
			}
		}

		stage("Build test") {
			parallel {
				stage("autotools") {
					agent any
					environment {
						FLAVOR = "autotools"
					}
					steps {
						cleanWs()
						unstash "build"
						sh "tar xaf ${targetDirectory}.tar.gz"
						dir("sword-scripts") {
							checkout scm
						}
						dir(targetDirectory) {
							sh "${WORKSPACE}/sword-scripts/scripts/autobuild.sh"
						}
						sh "${WORKSPACE}/sword-scripts/scripts/test.sh"
					}
				}
				stage("CMake") {
					agent any
					environment {
						FLAVOR = "cmake"
					}
					steps {
						cleanWs()
						unstash "build"
						sh "tar xaf ${targetDirectory}.tar.gz"
						dir("sword-scripts") {
							checkout scm
						}
						dir(targetDirectory) {
							sh "${WORKSPACE}/sword-scripts/scripts/cmake.sh"
						}
						sh "${WORKSPACE}/sword-scripts/scripts/test.sh"
					}
				}
			}
		}

		stage("Deploy artifact") {
			steps {
				cleanWs()
				unstash "build"
				archiveArtifacts "${targetDirectory}.tar.gz"
				sh "${WORKSPACE}/sword-scripts/scripts/release.sh"
			}
		}
	}
}
